// react/src/components/user/code-button.tsx
import http from "@/http/http";
import React, {useEffect, useRef} from "react";
import {HttpFetchConfig} from "js-http-fetch/types/types";

interface Props {
  validator: () => boolean
  requestConfig: HttpFetchConfig
}

function CodeButton(props: Props) {
  const btnRef = useRef(null)
  const text = '发送验证码'
  const intervalTime = 60
  let timer: number, time = useRef(0)
  useEffect(() => {
    const clickTime = parseInt(localStorage.getItem('code') || '0', 36) || 0
    time.current = Math.floor((Date.now() - clickTime) / 1000)
    if (time.current <= intervalTime) {
      time.current = intervalTime - time.current
      checkBtn(btnRef.current as unknown as HTMLElement)
    }
    // eslint-disable-next-line
  }, [])

  function handleClick(e: React.MouseEvent<HTMLElement>) {
    e.preventDefault()
    if (!props.validator()) return
    http(props.requestConfig).then(() => {
      time.current = intervalTime
      localStorage.setItem('code', Date.now().toString(36))
      checkBtn(btnRef.current as unknown as HTMLElement)
    })
  }

  function checkBtn(btn: HTMLElement) {
    btn.innerText = text + '（' + time.current + '）'
    btn.setAttribute('disabled', '')
    btn.classList.add('adm-button-disabled')
    timer = window.setInterval(() => {
      time.current--
      if (time.current !== 0) {
        btn.innerText = text + '（' + time.current + '）'
      } else {
        btn.removeAttribute('disabled')
        btn.classList.remove('adm-button-disabled')
        btn.innerText = text
        clearInterval(timer)
      }
    }, 1000)
  }

  return <button className='adm-button adm-button-primary adm-button-small adm-button-shape-default' onClick={handleClick} ref={btnRef}>{text}</button>
}

CodeButton.defaultProps = {
  validator: () => true
}
export default CodeButton

// vue/src/components/user/code-button.vue
<template>
  <button class="van-button van-button--primary van-button--small" @click="handleClick" ref="btnRef">{{ text }}</button>
</template>

<script lang="ts" setup>
import {defineProps, onMounted, ref, withDefaults} from 'vue'
import http from '@/http/http'
import {HttpFetchConfig} from 'js-http-fetch/types/types'

const btnRef = ref()

const props = withDefaults(defineProps<{
  validator: () => boolean
  requestConfig: HttpFetchConfig
}>(), {
  validator: () => true,
})
const text = '发送验证码'
const intervalTime = 60
let timer: number, time: number
onMounted(() => {
  const clickTime = parseInt(localStorage.getItem('code') || '0', 36) || 0
  time = Math.floor((Date.now() - clickTime) / 1000)
  if (time <= intervalTime) {
    time = intervalTime - time
    checkBtn(btnRef.value)
  }
})

function handleClick(e: PointerEvent) {
  e.preventDefault()
  if (!props.validator()) return
  http(props.requestConfig).then(() => {
    time = intervalTime
    localStorage.setItem('code', Date.now().toString(36))
    checkBtn(btnRef.value)
  })
}

function checkBtn(btn: HTMLElement) {
  btn.innerText = text + '（' + time + '）'
  btn.setAttribute('disabled', '')
  btn.classList.add('van-button--disabled')
  timer = window.setInterval(() => {
    time--
    if (time !== 0) {
      btn.innerText = text + '（' + time + '）'
    } else {
      btn.removeAttribute('disabled')
      btn.classList.remove('van-button--disabled')
      btn.innerText = text
      clearInterval(timer)
    }
  }, 1000)
}
</script>
