// src/App.vue
<template>
  <div class="main">
    <router-view/>
    <van-tabbar v-if="!HIDE_MENU_PATH_SET.has($route.path)" route>
      <van-tabbar-item icon="home-o" :to="INDEX_PATH">首页</van-tabbar-item>
      <van-tabbar-item icon="search" dot :to="COMMUNITY_PATH">云社区</van-tabbar-item>
      <van-tabbar-item icon="friends-o" badge="5" :to="CREATION_PATH">云创作</van-tabbar-item>
      <van-tabbar-item icon="setting-o" badge="20">创作中心</van-tabbar-item>
    </van-tabbar>
  </div>
</template>
<script lang="ts" setup>
import {ref} from "vue";
import {HIDE_MENU_PATH_SET, INDEX_PATH, COMMUNITY_PATH, CREATION_PATH} from "@/router";

const active = ref(0)
</script>
<style lang="scss" scoped>
.main {
  padding: 0 15px;
  max-width: 750PX;
  max-height: 600PX;
}
</style>

// react/src/App.tsx
import React from 'react';
import {Route, Routes, Navigate, useLocation} from 'react-router-dom';
import {login, findPassword, register, HIDE_MENU_PATH_SET} from './router/router'
import {TabBar} from 'antd-mobile'
import {AppOutline, UnorderedListOutline, MessageOutline, UserOutline} from 'antd-mobile-icons'
import './App.scss'

function App() {
  console.log(useLocation())
  const tabs = [
    {
      key: '/home',
      title: '首页',
      icon: <AppOutline/>,
      badge: 5
    },
    {
      key: '/todo',
      title: '云社区',
      icon: <UnorderedListOutline/>,
      badge: '99+'
    },
    {
      key: '/message',
      title: '云创作',
      icon: <MessageOutline/>,
      badge: ''
    },
    {
      key: '/me',
      title: '创作中心',
      icon: <UserOutline/>,
      badge: ''
    },
  ]
  return (
    <div className="main">
      <Routes>
        <Route element={login.element} path={login.path}/>
        <Route element={findPassword.element} path={findPassword.path}/>
        <Route element={register.element} path={register.path}/>
        <Route element={<Navigate to={login.path} replace/>} path="/"/>
      </Routes>
      {
        HIDE_MENU_PATH_SET.has(useLocation().pathname) ? null :
          <TabBar>
            {tabs.map(item => (
              <TabBar.Item
                key={item.key}
                icon={item.icon}
                title={item.title}
                badge={item.badge}
              />
            ))}
          </TabBar>
      }
    </div>
  );
}

export default App;
