// src/views/user/FindPassword.vue
<template>
  <h3 class="title">找回密码</h3>
  <van-form>
    <van-cell-group inset @submit="findPassword">
      <van-field v-model="username" name="用户名" clearable label="用户名" placeholder="用户名" :rules="[{ required: true, message: '请填写用户名' }]"/>
      <van-field v-model="email" type="password" name="邮箱" clearable label="邮箱" placeholder="邮箱" :rules="[{ required: true, message: '请填写邮箱' }]"/>
      <van-field v-model="code" center clearable label="邮箱验证码" placeholder="邮箱验证码">
        <template #button>
          <van-button size="small" type="primary">发送验证码</van-button>
        </template>
      </van-field>
    </van-cell-group>
    <div style="margin: 16px;">
      <van-button type="primary" block round native-type="submit">提交</van-button>
      <div class="flex jst-cnt-between fs-14 mt-10">
        <router-link to="/login" class="co-blue">登录</router-link>
        <router-link to="/register" class="co-blue">注册</router-link>
      </div>
    </div>
  </van-form>
</template>

<script lang="ts" setup>
import {ref} from "vue";

const username = ref('')
const email = ref('')
const code = ref('')

function findPassword() {
  console.log('找回密码')
}
</script>

<style lang="scss" scoped>
@import "~@/assets/css/public.scss";

.title {
  color: $primary-color;
  margin-top: 150px;
  margin-bottom: 50px;
  text-align: center;
}
</style>

// react/src/views/user/find-password/find-password.tsx
import React from "react";
import {Button, Form, Input} from "antd-mobile";
import {Link} from "react-router-dom";
import './find-password.scss'
import {FindPasswordFrom} from "./find-password-types";

export default function FindPassword() {

  function onFinish(data: FindPasswordFrom) {
    console.log(arguments)
  }

  return (
    <div className='find-password-box'>
      <h3 className='title'>找回密码</h3>
      <Form onFinish={onFinish} layout='horizontal' footer={
        <div>
          <Button shape='rounded' block type='submit' color='primary' size='middle'>提交</Button>
          <div className='flex jst-cnt-between fs-14 mt-10'>
            <Link to='/login' className='co-blue'>登录</Link>
            <Link to='/register' className='co-blue'>注册</Link>
          </div>
        </div>
      }>
        <Form.Item name='username' label='用户名' rules={[{required: true, message: '请填写用户名'}]}>
          <Input placeholder='请输入用户名'/>
        </Form.Item>
        <Form.Item name='email' label='邮箱' rules={[{required: true, message: '请填写邮箱'}]}>
          <Input placeholder='请输入邮箱' clearable type='password'/>
        </Form.Item>
        <Form.Item
          name='code'
          label='邮箱验证码'
          rules={[{required: true, message: '请填写验证码'}]}
          extra={
            <div className='extraPart'>
              <Button color='primary' size='small'>发送验证码</Button>
            </div>
          }
        >
          <Input placeholder='请输入验证码' clearable/>
        </Form.Item>
      </Form>
    </div>
  )
}
